#Show enchantment properties like tradeable and enchantable
#Will not work when Apotheosis is installed
showEnchProperties = true
#Which side of the screen to place the refresh button
#Allowed Values: LEFT, RIGHT
buttonSide = "LEFT"

