modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="dimensionworks_cave_factory"
version="0.1.0"
displayName="DimensionWorks Cave Factory"
authors="szx-jn"
description='''Unified cave-dimension factories for DimensionWorks.'''
[[dependencies.dimensionworks_cave_factory]]
modId="forge"
mandatory=true
versionRange="[47.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.dimensionworks_cave_factory]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.dimensionworks_cave_factory]]
modId="create"
mandatory=true
versionRange="[6.0.8,6.1)"
ordering="BEFORE"
side="BOTH"
[[dependencies.dimensionworks_cave_factory]]
modId="dimensionworks_rpm_limit"
mandatory=true
versionRange="[0.4.4,1.0)"
ordering="AFTER"
side="BOTH"
[[dependencies.dimensionworks_cave_factory]]
modId="alexscaves"
mandatory=true
versionRange="[2.0.2,3.0)"
ordering="AFTER"
side="BOTH"
[[dependencies.dimensionworks_cave_factory]]
modId="alex_caves_dimensions"
mandatory=true
versionRange="[1.0.4,2.0)"
ordering="AFTER"
side="BOTH"
[[dependencies.dimensionworks_cave_factory]]
modId="jei"
mandatory=false
versionRange="[15.20.0,16.0)"
ordering="AFTER"
side="CLIENT"
[[dependencies.dimensionworks_cave_factory]]
modId="jade"
mandatory=false
versionRange="[11.13.0,12.0)"
ordering="AFTER"
side="BOTH"
