modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="dimensionworks_transfer"
version="0.2.0"
displayName="DimensionWorks Transfer"
authors="szx-jn"
description='''Per-player isolated transfer dimension (dw:transfer) for DimensionWorks.'''
[[dependencies.dimensionworks_transfer]]
modId="forge"
mandatory=true
versionRange="[47.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.dimensionworks_transfer]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
