#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Sep 28 14:45:36 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.9.3.zip
enableShaders=true
